name: hello world

on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Displays Hello World Message
        run: echo "Hello world, Linda"
      - name: Another task
        run: echo "Anotehr task"

