name: variable and secrets
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Printing variable and secret
        run: |
          echo "The variable is: ${{vars.MY_VARIABLE}}"  
          echo "The secret is: ${{secrets.CONNECTION_STRING}}"
      # MY_VARIABLE
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: execute the JS code
        run: node variables.js
        env:
          MY-VARIABLE: ${{vars.MY-VARIABLE}}
        
   



          
