name: Variables
on:
  workflow_dispatch:

env:
  global_variable: GLOBAL VARIABLE # to be used anywhere here
jobs:
  job-1:
    runs-on: ubuntu-latest
    env:
      job_variable: JOB VARIABLE # available only for the job-1 section
    steps:
      - name: step 1 of job-1
        run: |
          echo "the value of the global variable is: ${{env.global_variable}}"
          echo "the value of the job variable is: ${{env.job_variable}}"
          echo "the value of the step variable is: {{env.step_variable}}"
        env:
          step_variable: STEP VARIABLE # available only for the steps section
          
          
          
